### ISSUE TITLE
screen size & rotation

### ISSUE THREAD

**Issue by ghost** [gloglas/rpi_gui#2]
Trying to get this to work with the [1.3inch LCD HAT from Waveshare](https://www.waveshare.com/wiki/1.3inch_LCD_HAT)
I have made a few tweaks to get it to display, but everything is rotated 90degrees counter clockwise.

Just wondering if there is a simple way to rotate the display so it shows up properly on my lcd screen?

_Found the answer: Changed the variable SCAN_DIR_DFT_

**Comment by gloglas** [comment]
Glad you found your answer!
